"""
Merge multiple word frequency comparison files into a unified table.

This script takes multiple TSV comparison files (generated by compare_freqs.py)
and merges them into a single table with unified column naming.

Usage:
    python -m jargon.keyness.merge_comparisons -i FILE1 FILE2 ... -o OUTPUT

Example:
    python -m jargon.keyness.merge_comparisons \\
        --input pubmed-v-leipzig.tsv pubmed-v-wiki.tsv msd-v-leipzig.tsv \\
        --output merged_comparisons.tsv \\
        --join-type outer
"""

import argparse
import sys
import pandas as pd
from pathlib import Path

from .io_utils import (
    extract_comparison_name,
    rename_columns_with_comparison,
    validate_comparison_files
)


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description='Merge multiple word frequency comparison files into a unified table.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Join Types:
    outer: Include all tokens from all files (NaN for missing values)
    inner: Only include tokens present in all files

Output Format:
    Columns are renamed to include comparison names:
    - abs-freq_{corpus}: Absolute frequency in corpus
    - {comparison}_{metric}: Metric value for comparison

    Example:
        token    abs-freq_pubmed    pubmed-v-leipzig_ll    pubmed-v-wiki_or
        plasma   262440             561341.59              244.53

Examples:
    # Merge three comparisons
    python -m jargon.keyness.merge_comparisons \\
        -i comp1.tsv comp2.tsv comp3.tsv \\
        -o merged.tsv

    # Inner join with zero for missing values
    python -m jargon.keyness.merge_comparisons \\
        -i comp1.tsv comp2.tsv \\
        -o merged.tsv \\
        --join-type inner --fill-value 0
        """
    )

    # Required arguments
    parser.add_argument(
        '-i', '--input',
        type=str,
        nargs='+',
        required=True,
        help='Input comparison TSV files (multiple)'
    )
    parser.add_argument(
        '-o', '--output',
        type=str,
        required=True,
        help='Output merged TSV file path'
    )

    # Optional arguments
    parser.add_argument(
        '-j', '--join-type',
        type=str,
        choices=['outer', 'inner'],
        default='outer',
        help='Join strategy: outer (default) or inner'
    )
    parser.add_argument(
        '--fill-value',
        type=str,
        choices=['nan', '0', 'null'],
        default='nan',
        help='Value for missing entries (default: nan)'
    )
    parser.add_argument(
        '-v', '--verbose',
        action='store_true',
        help='Verbose output'
    )

    return parser.parse_args()


def load_and_rename_comparison(
    filepath: Path,
    verbose: bool = False
) -> pd.DataFrame:
    """
    Load a comparison TSV file and rename columns with comparison name.

    Parameters
    ----------
    filepath : Path
        Path to comparison TSV file.
    verbose : bool, optional
        Print detailed information.

    Returns
    -------
    pd.DataFrame
        DataFrame with renamed columns, indexed by token.
    """
    # Extract comparison name from filename
    comparison_name = extract_comparison_name(filepath)

    if verbose:
        print(f"  Loading: {filepath.name}")
        print(f"  Comparison name: {comparison_name}")

    # Load TSV
    df = pd.read_csv(filepath, sep='\t')

    # Set token as index
    if 'token' not in df.columns:
        raise ValueError(f"File {filepath} missing 'token' column")

    df = df.set_index('token')

    # Rename columns to include comparison name
    df = rename_columns_with_comparison(df, comparison_name)

    if verbose:
        print(f"  Tokens: {len(df):,}")
        print(f"  Columns: {list(df.columns)}")
        print()

    return df


def merge_dataframes(
    dfs: list[pd.DataFrame],
    join_type: str,
    verbose: bool = False
) -> pd.DataFrame:
    """
    Merge multiple dataframes.

    Parameters
    ----------
    dfs : list[pd.DataFrame]
        List of dataframes to merge.
    join_type : str
        'outer' or 'inner'.
    verbose : bool, optional
        Print detailed information.

    Returns
    -------
    pd.DataFrame
        Merged dataframe.
    """
    if not dfs:
        raise ValueError("No dataframes to merge")

    if len(dfs) == 1:
        return dfs[0]

    if verbose:
        print(f"Merging {len(dfs)} dataframes with {join_type} join...")

    # Merge all dataframes
    merged = pd.concat(dfs, axis=1, join=join_type)

    if verbose:
        print(f"  Merged tokens: {len(merged):,}")
        print(f"  Total columns: {len(merged.columns):,}")

    return merged


def apply_fill_value(
    df: pd.DataFrame,
    fill_value: str,
    verbose: bool = False
) -> pd.DataFrame:
    """
    Apply fill value for missing entries.

    Parameters
    ----------
    df : pd.DataFrame
        Dataframe to fill.
    fill_value : str
        'nan', '0', or 'null'.
    verbose : bool, optional
        Print detailed information.

    Returns
    -------
    pd.DataFrame
        Dataframe with filled values.
    """
    if fill_value == 'nan':
        # pandas default, nothing to do
        if verbose:
            print("Keeping NaN for missing values")
        return df
    elif fill_value == '0':
        if verbose:
            print("Filling missing values with 0")
        return df.fillna(0)
    elif fill_value == 'null':
        if verbose:
            print("Filling missing values with empty string")
        return df.fillna('')
    else:
        raise ValueError(f"Invalid fill_value: {fill_value}")


def detect_duplicate_columns(df: pd.DataFrame, verbose: bool = False):
    """
    Detect and warn about duplicate column names.

    Parameters
    ----------
    df : pd.DataFrame
        Dataframe to check.
    verbose : bool, optional
        Print warnings.
    """
    if df.columns.duplicated().any():
        duplicates = df.columns[df.columns.duplicated()].unique()
        if verbose:
            print(f"\nWarning: Duplicate column names detected:")
            for dup in duplicates:
                print(f"  - {dup}")
            print("This may indicate overlapping comparisons or naming conflicts.")
            print()


def main():
    """Main function."""
    args = parse_args()

    # Convert paths
    input_paths = [Path(p) for p in args.input]
    output_path = Path(args.output)

    if args.verbose:
        print(f"Input files: {len(input_paths)}")
        for path in input_paths:
            print(f"  - {path}")
        print(f"Output: {output_path}")
        print(f"Join type: {args.join_type}")
        print(f"Fill value: {args.fill_value}")
        print()

    # Validate input files
    try:
        validate_comparison_files(input_paths)
    except Exception as e:
        print(f"Error validating input files: {e}", file=sys.stderr)
        sys.exit(1)

    # Load and rename all comparison files
    if args.verbose:
        print("Loading comparison files...\n")

    dfs = []
    for filepath in input_paths:
        try:
            df = load_and_rename_comparison(filepath, verbose=args.verbose)
            dfs.append(df)
        except Exception as e:
            print(f"Error loading {filepath}: {e}", file=sys.stderr)
            sys.exit(1)

    # Merge dataframes
    try:
        merged = merge_dataframes(dfs, args.join_type, verbose=args.verbose)
    except Exception as e:
        print(f"Error merging dataframes: {e}", file=sys.stderr)
        sys.exit(1)

    # Check for inner join with no overlapping tokens
    if args.join_type == 'inner' and len(merged) == 0:
        print("\nWarning: Inner join resulted in 0 tokens!", file=sys.stderr)
        print("No tokens are present in all input files.", file=sys.stderr)
        print("Consider using --join-type outer instead.", file=sys.stderr)
        sys.exit(1)

    # Detect duplicate columns
    detect_duplicate_columns(merged, verbose=args.verbose)

    # Apply fill value
    merged = apply_fill_value(merged, args.fill_value, verbose=args.verbose)

    # Create output directory if needed
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Write output
    try:
        merged.to_csv(output_path, sep='\t', index=True)
    except Exception as e:
        print(f"Error writing output: {e}", file=sys.stderr)
        sys.exit(1)

    # Print summary
    print(f"\nMerge complete!")
    print(f"  Input files: {len(input_paths)}")
    print(f"  Total tokens: {len(merged):,}")
    print(f"  Total columns: {len(merged.columns):,}")
    print(f"  Output written to: {output_path}")

    # Print column summary
    if args.verbose:
        print(f"\n  Columns:")
        for col in merged.columns:
            print(f"    - {col}")


if __name__ == '__main__':
    main()
